# ----------------------------------------------------------------------------#
#                                                                             #
#                              GemCrush config                                #
#                                                                             #
# ----------------------------------------------------------------------------#

# name of the language file (in the folder 'language')
#   the default.yml file is overwriten on every server restart! This means you will have to use the other files
#     to customize the messages, but since i am adding messages regulary in updates 
#   You should use the default file if you just want to have the up to date english default messages
langFile: 'default.yml'

game:
  # number of moves in a default game
  moves: 20
  # time in ticks (20 ticks = 1 second) between two gem movements
  #   this is time each gem needs to fall down one row
  ticksBetweenMovement: 5
  # time in ticks (20 ticks = 1 second) between switching two gems and destroying the matched ones
  ticksBetweenSwitchAndDestroy: 20


# requires vault and an economy plugin
economy:
  enabled: false
  cost: 10
  reward:
    # reward intervalls the last number will be paid if a player finishes a game in the intervall
    #   of the key to the next key (for the last key the invervall goes to infinity)
    # You can add as many intervalls as you want to
    0: 0
    100: 100
    200: 200
    300: 300
    400: 400
    500: 500

# use 'Material:data' or 'ID:data'
# Some materials can not be displayed in an inventory, just test everything after changing
#   there are also some materials that don't work for this plugin (for example: snowball)
#   i'll try fixing that
# You are advised to use different materials.
# The displaynames have to be different for the game to work!
items:
  gem1:
    material: 'Diamond'
    displayName: "Diamond"
  gem2:
    material: 'EMERALD'
    displayName: 'Emerald'
  gem3:
    material: 'BLAZE_POWDER'
    displayName: 'Sparks'
  gem4:
    material: 'clay_ball'
    displayName: 'Pearl'
  gem5:
    material: 'gold_block'
    displayName: 'Gold'
  gem6:
    material: 'iron_block'
    displayName: 'Iron'

onGameEnd:
  dispatchCommands:
    enabled: true
    commands:
    - 'tell %player% congrats ;)'
    - 'tell %player% you scored %score%!'
  broadcast:
    enabled: true
    messages:
    - '%player% finished a game of &4Gem&2Crush&r with &2%score% &rpoints!'
    - 'Do &2/gc &rto prove that you are better ;)'

