# ----------------------------------------------------------------------------#
#                                                                             #
#                              GemCrush config                                #
#                                                                             #
# ----------------------------------------------------------------------------#

# name of the language file (in the folder 'language')
#   the default.yml file is overwriten on every server restart! This means you will have to use the other files
#     to customize the messages, but since i am adding messages regulary in updates 
#   You should use the default file if you just want to have the up to date english default messages
langFile: 'default.yml'

game:
  # number of moves in a default game
  moves: 20
  # time in ticks (20 ticks = 1 second) between two gem movements
  #   this is time each gem needs to fall down one row
  ticksBetweenMovement: 3
  # time in ticks (20 ticks = 1 second) between switching two gems and destroying the matched ones
  ticksBetweenSwitchAndDestroy: 7
  # number of different gems in a normal game
  #   This number HAS TO BE equal or smaller then the number of gems defined in the section normalGems below
  #   8 or 7 are good numbers. 7 is easier and the game has to shuffle less but 8 is a bit more challenging
  numberOfNormalGems: 8
  # customise bombs here
  #   they are spawned if you combine gems to the following kind of forms
  #
  #   x x x      x x x      x
  #     x        x        x x x
  #     x        x          x
  #
  bombs:
    enabled: true
    # ticks until the bomb explodes (startes counting AFTER all gems fell down and nothing else can break)
    ticksTillExplosion: 15
    pointsOnBreak: 20
    displayName: '&cBomb'
    lore:
    - '&r'
    - '&4Caution: &6explosive!'
  playSounds: true
  # if you want you can change the sound volume here
  soundVolume: 0.5



# requires vault and an economy plugin
#   to pay out the rewards from section 'onGameEnd' economy.enabled AND onGameEnd.pay have to be true
#   if economy.enabled is true players will pay the cost when starting a game
economy:
  enabled: false
  cost: 10


onGameEnd:
  pay: true
  sendMessages: false
  sendBroadcasts: false
  dispatchCommands: false
  giveItems: false
  restrictions:
    # players with bypass permission do not have to pay. Here you can set whether they also do not get any rewards.
    playersWithBypassDontGetRewards: true
    # restrict rewards to be only given one in a specific time frame
    #   times in this section have to be integers and are in MINUTES!
    #   to always pay out all rewards use 0
    timeIntervals:
      # cooldown for getting moneyrewards
      money: 0
      # cooldown for item rewards
      items: 0

  itemRewards:
    # add as many items as you want
    #   use the key (in the example below it's 'exampleItem') to set it as a reward in the scoreIntervals
    exampleItem:
      material: Stone:2
      lore:
      - "&3testing"
      - "blub"
      displayName: "Test &4item"
      # number of items
      count: 1


  scoreIntervals:
    # all keys have to be integers otherwise they will be ignored and a warning will be printed in the console

    # money is only paid if economy is enabled

    # You can add as many intervalls as you want to. The order of the intervalls doesn't matter
    #   the given reward/messages/commands/broadcasts will always be used if the game is finished with a score between the key and the
    #   next higher key. For the highest key the intervall goes to infinity
    # You can add a money-reward with money: x; messages to send to the player with messages: (as list);
    #   commands: (as a list); broadcast: (as list); items: (as a list of previously under 'onGameEnd.itemRewards' defined itemstacks)

    # use %player% for the players name and %score% for the score

    # FYI: there is a message in the language file that will always be send after a game
    #   only add aditional messages in this section
    0:
      money: 0
      messages:
      - ' &2you can do better than that...'
      - ' &4try again &1;)'
    100:
      money: 10
    200:
      money: 20
    300:
      money: 30
    400:
      money: 40
      commands:
      - 'tell %player% congrats ;)'
      - 'tell %player% you scored %score%!'
    500:
      money: 50
      messages:
      - ' &2%score% wow! &1Thats not bad ^^'
      # - ' &2You won a diamond'
      commands:
      - 'tell %player% you scored %score%!'
      # - 'give %player% diamond 1'
      broadcast:
      - '%player% finished a game of &2GemCrush&r with &2%score% &rpoints!'
      - 'Do &2/gc &rto prove that you are better ;)'
      items:
      #- 'exampleItem'
      #- 'yourOwnDefinedItemStack(define above in section onGameEnd.itemRewards)'



# use 'Material:data' or 'ID:data'
# Some materials can not be displayed in an inventory, just test everything after changing
# You are advised to use different materials.
# The displaynames have to be different for the game to work!
# Add as many gems as you want the game will choose random ones for every round
normalGems:
  gem1:
    material: 'Diamond'
    # use & for colors
    displayName: "&dDiamond"
    # optional custom number of points per destroyed gem of this type
    #   the default is 10 and is used if this option is not set
    pointsOnBreak: 10
    # optional probability for this gem to be used
    #   default is 1 and is used if this option is not set
    # This is NOT the probability for the gem to be used to fill an empty slot in the game
    #   this probability is used when the game decides which normal gems to use for the game
    probability: 2
  gem2:
    material: 'EMERALD'
    displayName: '&2Emerald'
    pointsOnBreak: 10
    probability: 1
  gem3:
    material: 'BLAZE_POWDER'
    displayName: '&eSparks'
    pointsOnBreak: 10
    probability: 1
  gem4:
    material: 'clay_ball'
    displayName: '&7Pearl'
  gem5:
    material: 'gold_block'
    displayName: '&6Gold'
  gem6:
    material: 'iron_block'
    displayName: '&fIron'
  gem7:
    material: 'bone'
    displayName: '&5Fossil'
  gem8:
    material: 'apple'
    displayName: '&cApple'
  gem9:
    material: 'anvil'
    displayName: '&8Anvil'
  gem10:
    material: 'structure_void'
    displayName: '&2Wheel'
  gem11:
    material: 'double_plant'
    displayName: '&6Amber'

