name: GemCrush
author: Nikl
main: me.nikl.gemcrush.Main
version: 0.3
commands:
  gemcrush:
    description: play the game
    usage: /gemcrush
    aliases: [gc]
permissions:
  gemcrush.*:
    description: Gives all permissions
    children:
      gemcrush.admin: true
  gemcrush.admin:
    description: Gives all permissions
    default: op
    children:
      gemcrush.play: true
      gemcrush.reload: true
  gemcrush.play:
    description: You are allowed to start a game
    default: true
  gemcrush.reload:
    description: You can reload the plugin
    